In [1]:
import sys
sys.path.append('../')

In [2]:
from pycode.dataset import Softargmax_dataset, Softargmax_dataset_VP, Softargmax_dataset_test, RLBench_dataset, RLBench_dataset_VP, RLBench_dataset_test
from pycode.config import _C as cfg
from torch.utils.data import DataLoader

kornia requires version >= 3.6. your version 3.6


In [3]:
train_dataset = RLBench_dataset(cfg,save_dataset=True,mode='train')
train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=0)

length of future is 3 frame
There is no json data
create json data
done
save json data
done


In [4]:
for i, data in enumerate(train_dataloader):
    if i % 1000 == 0:
        print(i)

tensor([[ 82.0240, 171.8308]], dtype=torch.float64)
tensor([[ 82.5843, 172.8987]], dtype=torch.float64)
tensor([[ 83.1969, 173.9621]], dtype=torch.float64)
tensor([[ 83.8300, 174.9818]], dtype=torch.float64)
tensor([[ 84.4107, 175.8568]], dtype=torch.float64)
0
tensor([[139.7834, 184.9062]], dtype=torch.float64)
tensor([[139.7518, 186.8425]], dtype=torch.float64)
tensor([[139.7273, 188.3301]], dtype=torch.float64)
tensor([[139.7118, 189.3543]], dtype=torch.float64)
tensor([[139.7059, 189.9194]], dtype=torch.float64)
tensor([[147.6950, 157.2754]], dtype=torch.float64)
tensor([[147.6032, 155.0005]], dtype=torch.float64)
tensor([[147.4937, 152.2884]], dtype=torch.float64)
tensor([[147.3764, 149.3547]], dtype=torch.float64)
tensor([[147.2555, 146.3273]], dtype=torch.float64)
tensor([[ 76.1995, 141.0003]], dtype=torch.float64)
tensor([[ 78.2354, 142.7265]], dtype=torch.float64)
tensor([[ 80.3593, 144.3904]], dtype=torch.float64)
tensor([[ 82.5767, 145.9879]], dtype=torch.float64)
tensor([[ 

tensor([[125.3817, 176.6763]], dtype=torch.float64)
tensor([[125.3772, 178.3409]], dtype=torch.float64)
tensor([[130.8812, 139.8396]], dtype=torch.float64)
tensor([[131.1675, 143.6497]], dtype=torch.float64)
tensor([[131.4648, 147.4736]], dtype=torch.float64)
tensor([[131.7642, 151.3202]], dtype=torch.float64)
tensor([[132.0560, 155.2160]], dtype=torch.float64)
tensor([[113.7545, 112.2382]], dtype=torch.float64)
tensor([[112.9248, 114.6988]], dtype=torch.float64)
tensor([[112.0783, 117.1897]], dtype=torch.float64)
tensor([[111.2090, 119.7616]], dtype=torch.float64)
tensor([[110.3280, 122.3610]], dtype=torch.float64)
tensor([[ 64.7236, 165.0302]], dtype=torch.float64)
tensor([[ 64.7324, 165.1517]], dtype=torch.float64)
tensor([[ 64.6820, 165.4624]], dtype=torch.float64)
tensor([[ 64.5682, 166.0183]], dtype=torch.float64)
tensor([[ 64.3912, 166.8487]], dtype=torch.float64)
tensor([[171.8567, 195.4713]], dtype=torch.float64)
tensor([[171.8310, 195.7086]], dtype=torch.float64)
tensor([[171

KeyboardInterrupt: 

In [4]:
len(train_dataset)

1632782

In [5]:
train_dataset.data_dict['index_list']

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
